AUTO_CLEAR_VAR_SUBSCRIPTIONS_ON_CONNECT: bool = True
AUTO_CLEAR_VAR_MSG_BY_SUBSCRIPTION_ON_CONNECT: bool = True

AUTO_SUBSCRIBE_TO_BALANCE: bool = True
AUTO_SUBSCRIBE_TO_TRANSACTION: bool = True

AUTO_REMOVE_SUBSCRIPTION_ID_ON_FORGET_RESPONSE = True
STORE_MSG_BY_SUBSCRIPTION = True
# TODO: To avoid memory leaks
# IGNORE_MSG_BY_SUBSCRIPTION_FOR_TYPES = ['proposal']
