AUTO_CLEAR_VAR_SUBSCRIPTIONS_ON_CONNECT: bool = True
AUTO_CLEAR_VAR_MSG_BY_SUBSCRIPTION_ON_CONNECT: bool = True

AUTO_SUBSCRIBE_TO_BALANCE_ON_CONNECT: bool = True
AUTO_SUBSCRIBE_TO_TRANSACTION_ON_CONNECT: bool = True

AUTO_REMOVE_SUBSCRIPTION_ID_ON_FORGET_RESPONSE: bool = True
STORE_MSG_BY_SUBSCRIPTION: bool = True
# TODO: To avoid memory leaks
# IGNORE_MSG_BY_SUBSCRIPTION_FOR_TYPES = ['proposal']
